apiVersion: v1
kind: Service
metadata:
  name: redis-service  # The host ! Same key in python
spec:
  ports:
  - port: 4321  # The port ! Same as in python
    targetPort: 6379 # The default redis port
  selector:
    app: redis  # Which pods are concerned