apiVersion: v1
kind: Pod
metadata:
  name: redis-feeder
spec:
  containers:
    - name: redis-feeder
      image: redis_feeder:latest
      imagePullPolicy: Never  # Use local image
      args: ["Cerebral", "Bore"]  # Random arguments
      env:
        - name: ENVIRONMENT
          value: "preproduction"  # Environment variable
  restartPolicy: OnFailure  # To avoid Kubernetes to keep the Pod retrying