apiVersion: v1
kind: Pod
metadata:
  name: cron-code-test
spec:
  containers:
    - name: cron-code-test
      image: cron_code:latest
      imagePullPolicy: Never    
      args: ["Cerebral", "Bore"]
      env:
        - name: ENVIRONMENT
          value: "preproduction"
  restartPolicy: OnFailure