apiVersion: v1
kind: Pod
metadata:
  name: redis-server
  labels:
    app: redis # to make the service work
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: tutorial-storage-claim
  containers:
    - name: redis-server
      image: redis:alpine3.10

      volumeMounts:
        - mountPath: "/data"
          name: storage
