apiVersion: v1
kind: PersistentVolume
metadata:
  name: tutorial-storage
spec:
  storageClassName: youhou
  capacity:
    storage: 0.1M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kubernetes_infra_tutorial"  # our local directory