apiVersion: v1
kind: Pod
metadata:
  name: redis-server
  labels:
    app: redis # to make the service work
spec:
  containers:
    - name: redis-server
      image: redis:alpine3.10
      args: ["--appendonly", "yes"]

      volumeMounts:
        - mountPath: "/data"  # on the pod
          name: my-redis-storage

  volumes:
    - name: my-redis-storage
      persistentVolumeClaim:
        claimName: tutorial-storage-claim
